run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - typecheck
    - gofmt
    - goimports
    - misspell
    - gocritic
    - gosimple

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - commentFormatting
      - whyNoLint

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
