version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: tmux-a2a-postman
    binary: tmux-a2a-postman
    main: ./
    ldflags:
      - -s -w
      - -X internal/version.Version={{.Version}}
      - -X internal/version.Commit={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: tmux-a2a-postman
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: i9wa4
    name: tmux-a2a-postman
  draft: false
  prerelease: auto
  # NOTE: Tag and release are created by scripts/upsert-gh-release.sh
  # GoReleaser only builds and uploads assets to the existing release

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
  groups:
    - title: Features
      regexp: "^feat:"
      order: 0
    - title: Bug Fixes
      regexp: "^fix:"
      order: 1
    - title: Others
      order: 999
