package main

import (
	"fmt"
	"os"
)

func runHelp(args []string) {
	topics := []string{"messaging", "directories", "config", "commands"}
	printTopicList := func() {
		fmt.Println("Topics:")
		for _, t := range topics {
			fmt.Printf("  %-14s  tmux-a2a-postman help %s\n", t, t)
		}
	}

	if len(args) == 0 {
		fmt.Println("tmux-a2a-postman — A2A message routing daemon for tmux panes")
		fmt.Println("")
		fmt.Println("AI agents send and receive messages. Each message is routed to the recipient")
		fmt.Println("by the daemon. Use send-message to send and pop to read.")
		fmt.Println("")
		fmt.Println("Quick Start:")
		fmt.Println("  1. Start daemon:    tmux-a2a-postman start")
		fmt.Println("  2. Send a message:  tmux-a2a-postman send-message --to <node> --body \"text\"")
		fmt.Println("  3. Read next msg:   tmux-a2a-postman pop")
		fmt.Println("")
		fmt.Println("Key Concepts:")
		fmt.Println("  Node       An AI agent identified by its tmux pane title.")
		fmt.Println("  Edge       A bidirectional routing rule between two nodes (configured in edges).")
		fmt.Println("  Envelope   YAML frontmatter at the top of each message file:")
		fmt.Println("               ---")
		fmt.Println("               params:")
		fmt.Println("                 from: <sender>")
		fmt.Println("                 to: <recipient>")
		fmt.Println("                 timestamp: <ISO 8601>")
		fmt.Println("               ---")
		fmt.Println("")
		fmt.Println("Commands:")
		fmt.Println("  start                      Start the daemon (TUI dashboard)")
		fmt.Println("  stop                       Stop the running daemon for this tmux session")
		fmt.Println("  send-message               Send a message in one step (--to and --body required)")
		fmt.Println("  pop                        Read and archive the oldest unread inbox message")
		fmt.Println("  read                       List inbox message file paths")
		fmt.Println("  get-session-status-oneline Print pane status (emoji in pipes/tmux #(), ANSI in TTY)")
		fmt.Println("  get-session-health         Print session health per node")
		fmt.Println("  help [topic]               Show help (topics: messaging, directories, config, commands)")
		fmt.Println("")
		fmt.Println("Messaging Protocol:")
		fmt.Println("  send-message --to <node> --body \"text\"  Send a message in one step")
		fmt.Println("  pop                                      Read and archive oldest message")
		fmt.Println("")
		printTopicList()
		fmt.Println("")
		fmt.Println("Run `tmux-a2a-postman help <topic>` for detailed information.")
		return
	}

	topic := args[0]
	switch topic {
	case "messaging":
		fmt.Println("Messaging — send and receive messages")
		fmt.Println("")
		fmt.Println("Quick workflow (agents):")
		fmt.Println("  Send:  tmux-a2a-postman send-message --to <node> --body \"text\"")
		fmt.Println("  Read:  tmux-a2a-postman pop")
		fmt.Println("")
		fmt.Println("Reply workflow:")
		fmt.Println("  tmux-a2a-postman send-message --to <sender> --body \"DONE: ...\"")
		fmt.Println("")
		fmt.Println("  To reply in same context thread:")
		fmt.Println("    tmux-a2a-postman send-message --to <sender> --context-id <id> --body \"...\"")
		fmt.Println("    (context-id is auto-detected from the incoming message header)")
		fmt.Println("")
		fmt.Println("Envelope format (YAML frontmatter):")
		fmt.Println("  ---")
		fmt.Println("  params:")
		fmt.Println("    from: <sender node name>")
		fmt.Println("    to: <recipient node name>")
		fmt.Println("    timestamp: <ISO 8601 timestamp>")
		fmt.Println("  ---")
		fmt.Println("")
		fmt.Println("Sender is auto-detected from the tmux pane title (no --from flag).")
	case "directories":
		fmt.Println("Directories — session directory layout")
		fmt.Println("")
		fmt.Println("Base directory resolution (in priority order):")
		fmt.Println("  1. $POSTMAN_HOME environment variable")
		fmt.Println("  2. base_dir field in config file")
		fmt.Println("  3. $XDG_STATE_HOME/tmux-a2a-postman (default)")
		fmt.Println("     (falls back to ~/.local/state/tmux-a2a-postman)")
		fmt.Println("")
		fmt.Println("Layout:")
		fmt.Println("  {baseDir}/")
		fmt.Println("  └── {contextId}/")
		fmt.Println("      └── {sessionName}/")
		fmt.Println("          ├── draft/          # internal: draft staging area (use send-message instead)")
		fmt.Println("          ├── post/           # internal: outbox queue managed by postman daemon")
		fmt.Println("          ├── inbox/")
		fmt.Println("          │   └── {node}/     # daemon delivers messages here")
		fmt.Println("          ├── read/           # agent moves messages here after reading")
		fmt.Println("          ├── dead-letter/    # unroutable messages land here")
		fmt.Println("          └── waiting/        # per-node waiting state files")
	case "config":
		fmt.Println("Config — key configuration fields")
		fmt.Println("")
		fmt.Println("Config file: $XDG_CONFIG_HOME/tmux-a2a-postman/postman.toml")
		fmt.Println("            (falls back to ~/.config/tmux-a2a-postman/postman.toml)")
		fmt.Println("")
		fmt.Println("Key fields and defaults:")
		fmt.Println("  scan_interval      float64  1.0      Seconds between post/ scans")
		fmt.Println("  enter_delay        float64  0.5      Delay before sending tmux keys")
		fmt.Println("  tmux_timeout       float64  5.0      Timeout for tmux commands")
		fmt.Println("  startup_delay      float64  2.0      Delay before first scan")
		fmt.Println("  reminder_interval  float64  0.0      Idle reminder interval (0=disabled)")
		fmt.Println("  inbox_unread_threshold  int  3       Alert threshold for unread messages")
		fmt.Println("  edges              []string []       Allowed node-to-node routing pairs")
		fmt.Println("  edge_violation_warning_mode  string  \"compact\"  Warning verbosity")
		fmt.Println("")
		fmt.Println("Edge syntax (both separators create bidirectional routes):")
		fmt.Println("  edges = [")
		fmt.Println("    \"node-a -- node-b\",   # bidirectional: a<->b")
		fmt.Println("    \"node-b --> node-c\",  # also bidirectional: b<->c")
		fmt.Println("  ]")
		fmt.Println("")
		fmt.Println("Per-node configuration (TOML section):")
		fmt.Println("  [node-name]")
		fmt.Println("  role = \"description of node role\"")
		fmt.Println("  template = \"role template content\"")
	case "commands":
		fmt.Println("Commands — detailed command reference")
		fmt.Println("")
		fmt.Println("send-message")
		fmt.Println("  Compose and deliver a message atomically in a single command.")
		fmt.Println("  Flags:")
		fmt.Println("    --to <node>          Recipient node name (required)")
		fmt.Println("    --body <text>        Message body (required; replaces <!-- write here --> placeholder)")
		fmt.Println("    --context-id <id>    Context ID (optional, auto-detected)")
		fmt.Println("    --session <name>     tmux session name (optional, auto-detected)")
		fmt.Println("    --config <path>      Config file path (optional)")
		fmt.Println("  Example:")
		fmt.Println("    tmux-a2a-postman send-message --to orchestrator --body \"DONE: task complete\"")
		fmt.Println("")
		fmt.Println("pop")
		fmt.Println("  Read and archive the oldest unread inbox message.")
		fmt.Println("  Prints full message content to stdout; archives silently.")
		fmt.Println("  Node is auto-detected from tmux pane title.")
		fmt.Println("  Empty inbox: exits 0, prints 'No unread messages.' to stderr.")
		fmt.Println("  Flags:")
		fmt.Println("    --peek               Show without archiving (non-destructive)")
		fmt.Println("    --context-id <id>    Context ID (optional, auto-detected)")
		fmt.Println("    --config <path>      Config file path (optional)")
		fmt.Println("")
		fmt.Println("start")
		fmt.Println("  Start the tmux-a2a-postman daemon.")
		fmt.Println("  Flags:")
		fmt.Println("    --context-id <id>    Context ID (auto-generated if omitted)")
		fmt.Println("    --config <path>      Config file path (auto-detected from XDG_CONFIG_HOME)")
		fmt.Println("    --log-file <path>    Log file path (default: {baseDir}/{contextId}/postman.log)")
		fmt.Println("    --no-tui             Run without the TUI dashboard")
		fmt.Println("")
		fmt.Println("stop")
		fmt.Println("  Stop the running daemon for the current tmux session.")
		fmt.Println("  Sends SIGTERM and waits up to --timeout seconds (default 10) for exit.")
		fmt.Println("  Exits 0 if no daemon is running (idempotent).")
		fmt.Println("  Flags:")
		fmt.Println("    --session <name>     tmux session name (optional, auto-detected)")
		fmt.Println("    --config <path>      Config file path (optional)")
		fmt.Println("    --timeout <secs>     Seconds to wait for daemon exit (default 10)")
		fmt.Println("  NOTE: --timeout default (10s) is chosen to exceed the default tmux_timeout")
		fmt.Println("        (5s) plus goroutine drain margin. Increase if your config sets")
		fmt.Println("        tmux_timeout > 8s.")
		fmt.Println("")
		fmt.Println("get-session-status-oneline")
		fmt.Println("  Print all sessions' pane status on a single line.")
		fmt.Println("  TTY (interactive terminal): ANSI-colored dots matching the TUI.")
		fmt.Println("  Non-TTY (e.g. tmux status-right #()): plain emoji 🟢🔵🟡🔴.")
		fmt.Println("")
		fmt.Println("get-context-id")
		fmt.Println("  Print the live context ID for the current tmux session.")
		fmt.Println("  Useful for AI agents that need to discover context ID without flags.")
		fmt.Println("  Flags:")
		fmt.Println("    --session <name>     tmux session name (optional, auto-detected)")
		fmt.Println("    --config <path>      Config file path (optional)")
		fmt.Println("")
		fmt.Println("get-session-health")
		fmt.Println("  Print session health: node count, inbox/waiting counts per node.")
		fmt.Println("  Flags:")
		fmt.Println("    --config <path>      Config file path (optional)")
		fmt.Println("")
		fmt.Println("read")
		fmt.Println("  List inbox message file paths for the current node.")
		fmt.Println("  Node name is auto-detected from tmux pane title.")
		fmt.Println("  Flags:")
		fmt.Println("    --config <path>      Config file path (optional)")
		fmt.Println("")
		fmt.Println("help [topic]")
		fmt.Println("  Show help overview or detailed topic page.")
		fmt.Println("  Topics: messaging, directories, config, commands")
	default:
		fmt.Fprintf(os.Stderr, "unknown help topic: %q\n", topic)
		fmt.Fprintln(os.Stderr, "")
		fmt.Fprintln(os.Stderr, "Available topics:")
		for _, t := range topics {
			fmt.Fprintf(os.Stderr, "  %s\n", t)
		}
		os.Exit(1)
	}
}
